defaults: &defaults
  app_name: Zazo Notification
  version: 0.3.0
  authentication_method: digest
  stub_mobile_number: false
  notification_mailer:
    default_from: Sani Elfishawy <elfishawy.sani@gmail.com>
  rspec:
    profile_examples: 10

development:
  <<: *defaults
  authentication_method: basic
  stub_mobile_number: true

test:
  <<: *defaults

production:
  <<: *defaults
